### ISSUE TITLE
Fixing misleading error message in engineClass.py

### ISSUE THREAD

**Issue by Andimagandi** [plasmapotential/HEAT#42]
A misspelled PFC name in the PFC input file PFCs.csv leads to the AttributeError 'PFC' object has no attribute 'mapDirection'. A clear error message would be helpful.

**Comment by plasmapotential** [comment]
running a test yields the following output:
```
New mesh.  Creating...
Part S029_0221016_A_1-Tile 6 Layout Model050t not found in CAD.  Cannot Mesh!
No global mesh translations defined.
No Mesh for one of these objects.  Did you have a typo in input file?
Check HEAT output for Mesh Not Found errors
making STL directory
Writing mesh file: /root/HEAT/data/SPARC/STLs/S029_0221016_A_1-Tile 6 Layout Model050t___1.000000mm.stl
Traceback (most recent call last):
  File "/root/source/HEAT/source/launchHEAT.py", line 269, in <module>
    launchHEAT(args)
  File "/root/source/HEAT/source/launchHEAT.py", line 207, in launchHEAT
    tui.runSimulations()
  File "/root/source/HEAT/source/terminalUI.py", line 288, in runSimulations
    self.loadPFCs(PFCfiles[0])
  File "/root/source/HEAT/source/terminalUI.py", line 421, in loadPFCs
    self.ENG.getPFCinputs(defaultMask=False)
  File "/root/source/HEAT/source/engineClass.py", line 995, in getPFCinputs
    self.CAD.writeMesh2file(self.CAD.ROImeshes, self.CAD.ROI, self.CAD.ROIresolutions, path=self.CAD.STLpath)
  File "/root/source/HEAT/source/CADClass.py", line 691, in writeMesh2file
    mesh[i].write(filename)
AttributeError: 'str' object has no attribute 'write'

```

this seems like an ok error message so closing this issue for now.  if this situation persists, please submit a new ticket with an example and I will patch it in main.
